//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mentor.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sdb : DbContext
    {
        public sdb()
            : base("name=sdb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_student> tbl_student { get; set; }
        public virtual DbSet<tbl_teachers> tbl_teachers { get; set; }
        public virtual DbSet<tble_events> tble_events { get; set; }
        public virtual DbSet<tbl_admins> tbl_admins { get; set; }
        public virtual DbSet<tbl_category> tbl_category { get; set; }
        public virtual DbSet<tbl_img> tbl_img { get; set; }
        public virtual DbSet<tbl_courses> tbl_courses { get; set; }
        public virtual DbSet<View_courses> View_courses { get; set; }
        public virtual DbSet<View_teachers> View_teachers { get; set; }
        public virtual DbSet<tbl_Posts> tbl_Posts { get; set; }
        public virtual DbSet<tbl_Banners> tbl_Banners { get; set; }
        public virtual DbSet<tbl_About> tbl_About { get; set; }
        public virtual DbSet<tbl_pages> tbl_pages { get; set; }
        public virtual DbSet<tbl_Languages> tbl_Languages { get; set; }
    }
}
