//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mentor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_teachers
    {
        public string Name { get; set; }
        public string Family { get; set; }
        public Nullable<int> fkImg { get; set; }
        public int pkID { get; set; }
        public string address { get; set; }
        public string alt { get; set; }
        public string title { get; set; }
    }
}
