//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mentor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_courses
    {
        public int pkID { get; set; }
        public string title { get; set; }
        public int fkCat { get; set; }
        public string dis { get; set; }
        public Nullable<int> img { get; set; }
        public Nullable<int> fkTeacherID { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string catTitle { get; set; }
        public string address { get; set; }
        public string alt { get; set; }
        public string imgTitle { get; set; }
        public bool status { get; set; }
    }
}
