//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mentor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_courses
    {
        public int pkID { get; set; }
        public string title { get; set; }
        public int fkCat { get; set; }
        public string dis { get; set; }
        public Nullable<int> img { get; set; }
        public Nullable<int> fkTeacherID { get; set; }
        public bool status { get; set; }
    
        public virtual tbl_category tbl_category { get; set; }
        public virtual tbl_img tbl_img { get; set; }
        public virtual tbl_teachers tbl_teachers { get; set; }
    }
}
