//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mentor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Banners
    {
        public int pkID { get; set; }
        public string img { get; set; }
        public string Title { get; set; }
        public string Dis { get; set; }
        public string Url { get; set; }
        public string ButtonCaption { get; set; }
        public string imgAlt { get; set; }
        public string imgTitle { get; set; }
    }
}
