//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mentor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_blog
    {
        public int pkID { get; set; }
        public string Title { get; set; }
        public string Dis { get; set; }
        public string Contents { get; set; }
        public int fkWriter { get; set; }
        public System.DateTime DateOfWrite { get; set; }
        public string Image { get; set; }
        public string ImageTitle { get; set; }
        public string ImageAlt { get; set; }
        public string KeyWords { get; set; }
        public Nullable<int> fkLangID { get; set; }
    
        public virtual tbl_Languages tbl_Languages { get; set; }
        public virtual tbl_teachers tbl_teachers { get; set; }
    }
}
