//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mentor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_About
    {
        public int pkID { get; set; }
        public string Items { get; set; }
        public string Image { get; set; }
        public string ImageAlt { get; set; }
        public string ImageTitle { get; set; }
        public string ButtonCaption { get; set; }
        public string ButtonUrl { get; set; }
        public string Title { get; set; }
        public string Dis { get; set; }
    }
}
